CREATE SCHEMA IF NOT EXISTS totvs;

SET SCHEMA totvs;

CREATE TABLE TABLE_CLIENTE (
   ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
   NOME_CLIENTE VARCHAR(255) NOT NULL,
   CPF_CLIENTE VARCHAR(14) NOT NULL UNIQUE ,
   ENDERECO_CLIENTE VARCHAR(255),
   BAIRRO_CLIENTE VARCHAR(100)
);

CREATE TABLE TABLE_TELEFONE (
    ID_TELEFONE INT AUTO_INCREMENT PRIMARY KEY,
    NUMR_TELEFONE VARCHAR(20) UNIQUE,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TABLE_CLIENTE(ID_CLIENTE)
);
